site_name: "Epigraph"
site_description: "An engraving in web's history"
site_author: "Volatus"
copyright: "&copy; 2021 Lucas B. \"Volatus\" Martins. Some rights reserved."

nav:
  - "Home": "index.md"

markdown_extensions:
  - footnotes
  - def_list
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.inlinehilite
  - pymdownx.superfences

theme:
  name: null
  custom_dir: "epigraph/"
  features:
    - content.code.annotate
